using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using PingMonitor.Web.Data;
using PingMonitor.Web.Models;
using PingMonitor.Web.Services.AiChat;
using PingMonitor.Web.Services.StartupGate;
using PingMonitor.Web.Services.Telegram;
namespace PingMonitor.Web.Services.AiEventTasks;
internal sealed class AiEventTriggeredTaskWorker : BackgroundService
{
    private readonly IServiceScopeFactory _scopeFactory; private readonly IStartupGateRuntimeState _startupGate; private readonly ILogger<AiEventTriggeredTaskWorker> _logger; private readonly SemaphoreSlim _concurrency=new(1,1);
    public AiEventTriggeredTaskWorker(IServiceScopeFactory scopeFactory,IStartupGateRuntimeState startupGate,ILogger<AiEventTriggeredTaskWorker> logger){_scopeFactory=scopeFactory;_startupGate=startupGate;_logger=logger;}
    protected override async Task ExecuteAsync(CancellationToken stoppingToken){using var timer=new PeriodicTimer(TimeSpan.FromSeconds(30)); while(!stoppingToken.IsCancellationRequested){if(_startupGate.IsOperationalMode) await RunPendingAsync(stoppingToken); await timer.WaitForNextTickAsync(stoppingToken);}}
    internal async Task RunPendingAsync(CancellationToken ct){if(!_startupGate.IsOperationalMode)return; if(!await _concurrency.WaitAsync(0,ct))return; try{await using var scope=_scopeFactory.CreateAsyncScope(); var db=scope.ServiceProvider.GetRequiredService<PingMonitorDbContext>(); var run=await db.AiEventTriggeredTaskRuns.Where(x=>x.Status==AiEventTriggeredTaskRunStatus.Pending).OrderBy(x=>x.CreatedAtUtc).FirstOrDefaultAsync(ct); if(run is null)return; var task=await db.AiEventTriggeredTasks.FirstOrDefaultAsync(x=>x.AiEventTriggeredTaskId==run.TaskId,ct); if(task is null||!task.Enabled){run.Status=AiEventTriggeredTaskRunStatus.Skipped;run.CompletedAtUtc=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);return;} var now=DateTimeOffset.UtcNow; run.Status=AiEventTriggeredTaskRunStatus.Running; run.StartedAtUtc=now; task.LastStatus=AiEventTriggeredTaskRunStatus.Running; task.LastRunAtUtc=now; task.UpdatedAtUtc=now; await db.SaveChangesAsync(ct); try{var prompt=$"Event-triggered AI task prompt:\n{task.Prompt}\n\nStructured trigger context JSON:\n{run.TriggerContextJson}"; var principal=new ClaimsPrincipal(new ClaimsIdentity([new Claim(ClaimTypes.NameIdentifier,task.OwnerUserId)],"EventTriggeredAiTask")); var chat=scope.ServiceProvider.GetRequiredService<IAiChatService>(); var response=await chat.SendAsync(new AiChatRequest{Source=AiChatSource.EventTriggeredTask,UserMessage=prompt,ApplicationUserId=task.OwnerUserId,Principal=principal},ct); if(!response.Succeeded||string.IsNullOrWhiteSpace(response.AssistantMessage))throw new InvalidOperationException(response.ErrorMessage??"AI provider did not return an event-triggered task response."); var telegram=scope.ServiceProvider.GetRequiredService<ITelegramDirectMessageSender>(); var send=await telegram.SendToUserAsync(task.OwnerUserId,$"Ping Monitor event-triggered AI task: {task.Name}\n\n{response.AssistantMessage}",ct); if(!send.Succeeded)throw new InvalidOperationException(send.Message); run.Status=AiEventTriggeredTaskRunStatus.Succeeded; task.LastStatus=AiEventTriggeredTaskRunStatus.Succeeded; task.LastSucceededAtUtc=DateTimeOffset.UtcNow; task.LastError=null; task.LastResponsePreview=Truncate(response.AssistantMessage,AiEventTriggeredTask.LastResponsePreviewMaxLength);}catch(Exception ex){_logger.LogWarning(ex,"Event-triggered AI task {TaskId} failed for owner {OwnerUserId}.",task.AiEventTriggeredTaskId,task.OwnerUserId); run.Status=AiEventTriggeredTaskRunStatus.Failed; run.Error=Truncate(ex.Message,AiEventTriggeredTaskRun.ErrorMaxLength); task.LastStatus=AiEventTriggeredTaskRunStatus.Failed; task.LastFailedAtUtc=DateTimeOffset.UtcNow; task.LastError=Truncate(ex.Message,AiEventTriggeredTask.LastErrorMaxLength);} run.CompletedAtUtc=DateTimeOffset.UtcNow; task.UpdatedAtUtc=run.CompletedAtUtc.Value; await db.SaveChangesAsync(ct);}finally{_concurrency.Release();}}
    private static string Truncate(string v,int max)=>v.Length<=max?v:v[..max];
}
