using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using PingMonitor.Web.Data;
using PingMonitor.Web.Models;
namespace PingMonitor.Web.Services.AiEventTasks;
internal sealed class AiEventTriggeredTaskService : IAiEventTriggeredTaskService
{
    private static readonly HashSet<string> EndpointStates = ["Up","Down","Suppressed","Degraded"];
    private static readonly HashSet<string> AgentStates = ["Online","Offline","Stale"];
    private readonly PingMonitorDbContext _db;
    public AiEventTriggeredTaskService(PingMonitorDbContext db)=>_db=db;
    public async Task<IReadOnlyList<AiEventTriggeredTaskDto>> ListForUserAsync(string ownerUserId,CancellationToken ct)=> (await _db.AiEventTriggeredTasks.AsNoTracking().Where(x=>x.OwnerUserId==ownerUserId).OrderBy(x=>x.Name).ToListAsync(ct)).Select(ToDto).ToArray();
    public async Task<AiEventTriggeredTaskDto?> GetForUserAsync(string ownerUserId,string taskId,CancellationToken ct){var e=await _db.AiEventTriggeredTasks.AsNoTracking().FirstOrDefaultAsync(x=>x.OwnerUserId==ownerUserId&&x.AiEventTriggeredTaskId==taskId,ct);return e is null?null:ToDto(e);}    
    public async Task<AiEventTriggeredTaskMutationResult> SaveAsync(SaveAiEventTriggeredTaskCommand c,CancellationToken ct){var err=await ValidateAsync(c,ct); if(err is not null)return new(false,err,null); var now=DateTimeOffset.UtcNow; var e=string.IsNullOrWhiteSpace(c.AiEventTriggeredTaskId)?new AiEventTriggeredTask{AiEventTriggeredTaskId=Guid.NewGuid().ToString("N"),OwnerUserId=c.OwnerUserId,CreatedAtUtc=now}:await _db.AiEventTriggeredTasks.FirstOrDefaultAsync(x=>x.OwnerUserId==c.OwnerUserId&&x.AiEventTriggeredTaskId==c.AiEventTriggeredTaskId,ct); if(e is null)return new(false,"Event-triggered AI task was not found for the current user.",null); if(_db.Entry(e).State==EntityState.Detached)_db.AiEventTriggeredTasks.Add(e); e.Name=c.Name.Trim(); e.Prompt=c.Prompt.Trim(); e.Enabled=c.Enabled; e.TriggerType=c.TriggerType; e.EndpointTargetStatesJson=JsonSerializer.Serialize(c.EndpointTargetStates.Distinct().ToArray()); e.AgentTargetStatesJson=JsonSerializer.Serialize(c.AgentTargetStates.Distinct().ToArray()); e.ScopeMode=c.ScopeMode; e.ScopeSelectionJson=JsonSerializer.Serialize(c.ScopeSelectionIds.Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct().ToArray()); e.RateLimitValue=c.RateLimitValue; e.RateLimitUnit=c.RateLimitUnit; e.DeliveryTarget=c.DeliveryTarget; e.UpdatedAtUtc=now; await _db.SaveChangesAsync(ct); return new(true,null,ToDto(e));}
    public async Task<AiEventTriggeredTaskMutationResult> DeleteAsync(string ownerUserId,string taskId,CancellationToken ct){var e=await _db.AiEventTriggeredTasks.FirstOrDefaultAsync(x=>x.OwnerUserId==ownerUserId&&x.AiEventTriggeredTaskId==taskId,ct); if(e is null)return new(false,"Event-triggered AI task was not found for the current user.",null); _db.AiEventTriggeredTasks.Remove(e); await _db.SaveChangesAsync(ct); return new(true,null,null);}    
    public async Task RecordEndpointStateChangedAsync(EndpointStateChangedAiEvent ev,CancellationToken ct){if(!EndpointStates.Contains(ev.NewState.ToString()))return; var endpointGroupIds = await _db.EndpointGroupMemberships.AsNoTracking().Where(x => x.EndpointId == ev.EndpointId).Select(x => x.GroupId).ToArrayAsync(ct); var tasks=await _db.AiEventTriggeredTasks.Where(x=>x.Enabled&&x.TriggerType==AiEventTriggerType.EndpointStateChanged).ToListAsync(ct); foreach(var t in tasks.Where(t=>MatchesEndpoint(t,ev,endpointGroupIds))){await QueueOrRateLimitAsync(t,JsonSerializer.Serialize(new{triggerType="EndpointStateChanged",endpoint=new{endpointId=ev.EndpointId,name=ev.EndpointName,target=ev.EndpointTarget},assignmentId=ev.AssignmentId,agentId=ev.AgentId,previousState=ev.PreviousState.ToString(),newState=ev.NewState.ToString(),transitionAtUtc=ev.TransitionAtUtc,matchedScope=t.ScopeMode.ToString(),rateLimit=new{minimumInterval=$"{t.RateLimitValue} {t.RateLimitUnit}",lastRunAtUtc=t.LastRunAtUtc}}),ct);} await _db.SaveChangesAsync(ct);}    
    public async Task RecordAgentStateChangedAsync(AgentStateChangedAiEvent ev,CancellationToken ct){if(!AgentStates.Contains(ev.NewStatus.ToString()))return; var tasks=await _db.AiEventTriggeredTasks.Where(x=>x.Enabled&&x.TriggerType==AiEventTriggerType.AgentStateChanged).ToListAsync(ct); foreach(var t in tasks.Where(t=>MatchesAgent(t,ev))){await QueueOrRateLimitAsync(t,JsonSerializer.Serialize(new{triggerType="AgentStateChanged",agent=new{agentId=ev.AgentId,name=ev.AgentName,instanceId=ev.InstanceId},previousState=ev.PreviousStatus.ToString(),newState=ev.NewStatus.ToString(),transitionAtUtc=ev.TransitionAtUtc,matchedScope=t.ScopeMode.ToString(),rateLimit=new{minimumInterval=$"{t.RateLimitValue} {t.RateLimitUnit}",lastRunAtUtc=t.LastRunAtUtc}}),ct);} await _db.SaveChangesAsync(ct);}    
    private async Task QueueOrRateLimitAsync(AiEventTriggeredTask t,string json,CancellationToken ct){var now=DateTimeOffset.UtcNow; t.LastTriggeredAtUtc=now; var min=t.RateLimitUnit switch{AiEventTriggerRateLimitUnit.Hours=>TimeSpan.FromHours(t.RateLimitValue),AiEventTriggerRateLimitUnit.Days=>TimeSpan.FromDays(t.RateLimitValue),_=>TimeSpan.FromMinutes(t.RateLimitValue)}; var pending=await _db.AiEventTriggeredTaskRuns.AnyAsync(x=>x.TaskId==t.AiEventTriggeredTaskId&&(x.Status==AiEventTriggeredTaskRunStatus.Pending||x.Status==AiEventTriggeredTaskRunStatus.Running),ct); if(pending || (t.LastRunAtUtc is not null && now-t.LastRunAtUtc.Value<min)){t.LastRateLimitedAtUtc=now; t.RateLimitedCount++; t.LastStatus=AiEventTriggeredTaskRunStatus.RateLimited; return;} _db.AiEventTriggeredTaskRuns.Add(new AiEventTriggeredTaskRun{AiEventTriggeredTaskRunId=Guid.NewGuid().ToString("N"),TaskId=t.AiEventTriggeredTaskId,TriggerType=t.TriggerType,TriggerContextJson=json,Status=AiEventTriggeredTaskRunStatus.Pending,CreatedAtUtc=now});}
    private static bool MatchesEndpoint(AiEventTriggeredTask t,EndpointStateChangedAiEvent e,IReadOnlyCollection<string> endpointGroupIds){if(!Read(t.EndpointTargetStatesJson).Contains(e.NewState.ToString()))return false; var ids=Read(t.ScopeSelectionJson); return t.ScopeMode switch{AiEventTriggerScopeMode.AllVisibleEndpoints=>true,AiEventTriggerScopeMode.SelectedEndpoints=>ids.Contains(e.EndpointId),AiEventTriggerScopeMode.SelectedEndpointGroups=>ids.Any(endpointGroupIds.Contains),AiEventTriggerScopeMode.EndpointsAssignedToSelectedAgents=>ids.Contains(e.AgentId),_=>false};}
    private bool MatchesAgent(AiEventTriggeredTask t,AgentStateChangedAiEvent e){if(!Read(t.AgentTargetStatesJson).Contains(e.NewStatus.ToString()))return false; var ids=Read(t.ScopeSelectionJson); return t.ScopeMode==AiEventTriggerScopeMode.AllVisibleAgents || (t.ScopeMode==AiEventTriggerScopeMode.SelectedAgents && ids.Contains(e.AgentId));}
    private async Task<string?> ValidateAsync(SaveAiEventTriggeredTaskCommand c,CancellationToken ct){if(string.IsNullOrWhiteSpace(c.Name)||c.Name.Trim().Length>AiEventTriggeredTask.NameMaxLength)return "Name is required and must be 128 characters or fewer."; if(string.IsNullOrWhiteSpace(c.Prompt)||c.Prompt.Trim().Length>AiEventTriggeredTask.PromptMaxLength)return "Prompt is required and must be 4000 characters or fewer."; if(!Enum.IsDefined(c.TriggerType))return "Trigger type is invalid."; if(c.RateLimitValue<1)return "Rate limit value must be at least 1."; if(!Enum.IsDefined(c.RateLimitUnit))return "Rate limit unit is invalid."; if(c.DeliveryTarget!=AiEventTriggeredTaskDeliveryTarget.TelegramOwner)return "Delivery target is invalid."; if(c.Enabled&&!await _db.TelegramAccounts.AsNoTracking().AnyAsync(x=>x.UserId==c.OwnerUserId&&x.Verified&&x.IsActive,ct))return "Link your Telegram account before enabling event-triggered AI tasks."; if(c.TriggerType==AiEventTriggerType.EndpointStateChanged){if(c.EndpointTargetStates.Count==0||c.EndpointTargetStates.Any(x=>!EndpointStates.Contains(x)))return "Select at least one endpoint target state."; if(c.ScopeMode is not (AiEventTriggerScopeMode.AllVisibleEndpoints or AiEventTriggerScopeMode.SelectedEndpoints or AiEventTriggerScopeMode.SelectedEndpointGroups or AiEventTriggerScopeMode.EndpointsAssignedToSelectedAgents))return "Endpoint scope is invalid.";} else {if(c.AgentTargetStates.Count==0||c.AgentTargetStates.Any(x=>!AgentStates.Contains(x)))return "Select at least one agent target state."; if(c.ScopeMode is not (AiEventTriggerScopeMode.AllVisibleAgents or AiEventTriggerScopeMode.SelectedAgents))return "Agent scope is invalid.";} return null;}
    private static string[] Read(string json){try{return JsonSerializer.Deserialize<string[]>(json)??[];}catch{return[];}}
    private static AiEventTriggeredTaskDto ToDto(AiEventTriggeredTask x)=>new(x.AiEventTriggeredTaskId,x.OwnerUserId,x.Name,x.Prompt,x.Enabled,x.TriggerType,Read(x.EndpointTargetStatesJson),Read(x.AgentTargetStatesJson),x.ScopeMode,Read(x.ScopeSelectionJson),x.RateLimitValue,x.RateLimitUnit,x.DeliveryTarget,x.LastTriggeredAtUtc,x.LastRunAtUtc,x.LastRateLimitedAtUtc,x.RateLimitedCount,x.LastStatus,x.LastError,x.LastResponsePreview,x.CreatedAtUtc,x.UpdatedAtUtc);
}
