using System.IO.Compression;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Hosting;

namespace PingMonitor.Web.Services;

internal sealed class AgentPackageBuilder : IAgentPackageBuilder
{
    private static readonly string[] RootFiles = [
        "README.md",
        "requirements.txt",
        "run-agent.cmd"
    ];

    private readonly IWebHostEnvironment _environment;
    private readonly ILogger<AgentPackageBuilder> _logger;

    public AgentPackageBuilder(IWebHostEnvironment environment, ILogger<AgentPackageBuilder> logger)
    {
        _environment = environment;
        _logger = logger;
    }

    public async Task<byte[]> BuildAsync(string serverUrl, string instanceId, string apiKey, CancellationToken cancellationToken)
    {
        var agentRoot = ResolveAgentRootPath();
        if (!Directory.Exists(agentRoot))
        {
            throw new InvalidOperationException($"Agent template directory was not found at '{agentRoot}'.");
        }

        await using var output = new MemoryStream();
        using var archive = new ZipArchive(output, ZipArchiveMode.Create, leaveOpen: true);

        foreach (var fileName in RootFiles)
        {
            var fullPath = Path.Combine(agentRoot, fileName);
            if (!File.Exists(fullPath))
            {
                throw new InvalidOperationException($"Required agent template file '{fileName}' was not found.");
            }

            await AddFileAsync(archive, fullPath, fileName, cancellationToken);
        }

        var appDirectory = Path.Combine(agentRoot, "app");
        if (!Directory.Exists(appDirectory))
        {
            throw new InvalidOperationException("Required agent app directory was not found.");
        }

        foreach (var filePath in Directory.EnumerateFiles(appDirectory, "*.py", SearchOption.AllDirectories).OrderBy(path => path, StringComparer.Ordinal))
        {
            var relativePath = Path.GetRelativePath(agentRoot, filePath).Replace('\\', '/');
            await AddFileAsync(archive, filePath, relativePath, cancellationToken);
        }

        var envContents = BuildEnvContents(serverUrl, instanceId, apiKey);
        var envEntry = archive.CreateEntry(".env");
        await using var envStream = envEntry.Open();
        await using var writer = new StreamWriter(envStream, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        await writer.WriteAsync(envContents.AsMemory(), cancellationToken);
        await writer.FlushAsync(cancellationToken);

        archive.Dispose();
        _logger.LogInformation("Built agent package for instance {InstanceId} from template {TemplatePath}", instanceId, agentRoot);
        return output.ToArray();
    }

    private string ResolveAgentRootPath()
    {
        var bundledTemplatePath = Path.Combine(_environment.ContentRootPath, "Agent");
        if (Directory.Exists(bundledTemplatePath))
        {
            return bundledTemplatePath;
        }

        return Path.GetFullPath(Path.Combine(_environment.ContentRootPath, "..", "..", "Agent"));
    }

    private static string BuildEnvContents(string serverUrl, string instanceId, string apiKey)
    {
        return string.Join('\n',
            "# Generated by PingMonitor deploy flow",
            $"SERVER_URL={serverUrl}",
            $"INSTANCE_ID={instanceId}",
            $"API_KEY={apiKey}",
            string.Empty);
    }

    private static async Task AddFileAsync(ZipArchive archive, string sourcePath, string entryName, CancellationToken cancellationToken)
    {
        var entry = archive.CreateEntry(entryName, CompressionLevel.Optimal);
        await using var entryStream = entry.Open();
        await using var fileStream = File.OpenRead(sourcePath);
        await fileStream.CopyToAsync(entryStream, cancellationToken);
    }
}
